//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatingDiary.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public Person()
        {
            this.Interests = new HashSet<Interest>();
            this.Dates = new HashSet<Date>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string SecondName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string FileName { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public string Age { get; set; }
        public string Town { get; set; }
        public string Country { get; set; }
        public Nullable<bool> IsFavourite { get; set; }
    
        public virtual ICollection<Interest> Interests { get; set; }
        public virtual ICollection<Date> Dates { get; set; }
    }
}
